### ISSUE TITLE
GEXF Layout Updated with Katy' Sample Data

### ISSUE THREAD

**Issue by mginda** [cns-iu/cns-pubvis#3]
- [ ] Update layout used for Katy.isi GEXF network layout.

**Comment by mginda** [comment]
Current GEXF file format is not working with my version of Gephi, so I cannot currently update layout.

**Comment by bherr2** [comment]
[low priority] @mginda when you get a chance, could you use katy's .isi file to generate a co-author network, load it into gephi, and then generate/upload the new gexp file to github.

https://github.com/cns-iu/cns-pubvis/blob/master/example/katy-borner_wos-extract-2018-08-21.isi
